CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(100) PRIMARY KEY, email VARCHAR(255) NOT NULL UNIQUE, name VARCHAR(255) NOT NULL,
  fullName VARCHAR(255), role VARCHAR(40) NOT NULL, phone VARCHAR(40), mobile VARCHAR(40),
  password_hash VARCHAR(255) NOT NULL, status VARCHAR(30) NOT NULL, created_at VARCHAR(64),
  createdAt VARCHAR(64), updated_at VARCHAR(64), updatedAt VARCHAR(64), INDEX idx_users_role_status (role, status)
);

CREATE TABLE IF NOT EXISTS leads (
  id VARCHAR(100) PRIMARY KEY, name VARCHAR(500), customer_name VARCHAR(500), mobile VARCHAR(100), customer_mobile VARCHAR(100), email VARCHAR(500), customer_email VARCHAR(500),
  status VARCHAR(500), qualification_status VARCHAR(500), budget DECIMAL(18,2), loan_required BOOLEAN,
  preferred_location VARCHAR(500), flat_type VARCHAR(500), timeline VARCHAR(500), purpose VARCHAR(500), city VARCHAR(500), project_name VARCHAR(500),
  configuration VARCHAR(500), source VARCHAR(500), assigned_to VARCHAR(100), interested_property VARCHAR(500), notes TEXT,
  created_at VARCHAR(64), updated_at VARCHAR(64), INDEX idx_leads_mobile (mobile), INDEX idx_leads_status (status)
);
CREATE TABLE IF NOT EXISTS follow_ups (id VARCHAR(100) PRIMARY KEY, lead_id VARCHAR(100), lead_name VARCHAR(500), customer_name VARCHAR(500), mobile VARCHAR(100), customer_mobile VARCHAR(100), customer_email VARCHAR(500), type VARCHAR(500), date VARCHAR(100), time VARCHAR(100), next_date VARCHAR(100), status VARCHAR(500), remarks TEXT, executive_id VARCHAR(100), executive_name VARCHAR(500), created_at VARCHAR(64), updated_at VARCHAR(64));
CREATE TABLE IF NOT EXISTS units (id VARCHAR(100) PRIMARY KEY, unit_number VARCHAR(500), flat_type VARCHAR(500), wing VARCHAR(500), floor INT, carpet_area DECIMAL(18,2), built_up_area DECIMAL(18,2), price DECIMAL(18,2), parking VARCHAR(500), amenities TEXT, facing VARCHAR(500), status VARCHAR(500), created_at VARCHAR(64), updated_at VARCHAR(64));
CREATE TABLE IF NOT EXISTS site_visits (id VARCHAR(100) PRIMARY KEY, lead_id VARCHAR(100), lead_name VARCHAR(500), customer_name VARCHAR(500), mobile VARCHAR(100), customer_mobile VARCHAR(100), customer_email VARCHAR(500), project_name VARCHAR(500), visit_date VARCHAR(100), visit_time VARCHAR(100), pickup_required BOOLEAN, status VARCHAR(500), feedback TEXT, executive_id VARCHAR(100), executive_name VARCHAR(500), created_at VARCHAR(64), updated_at VARCHAR(64));
CREATE TABLE IF NOT EXISTS negotiations (id VARCHAR(100) PRIMARY KEY, lead_id VARCHAR(100), lead_name VARCHAR(500), customer_name VARCHAR(500), mobile VARCHAR(100), customer_mobile VARCHAR(100), customer_email VARCHAR(500), project_name VARCHAR(500), unit_id VARCHAR(100), unit_number VARCHAR(500), unit_name VARCHAR(500), offered_price DECIMAL(18,2), discount DECIMAL(18,2), special_offer TEXT, payment_mode VARCHAR(500), payment_reference VARCHAR(500), approval_status VARCHAR(500), remarks TEXT, status VARCHAR(500), created_at VARCHAR(64), updated_at VARCHAR(64));
CREATE TABLE IF NOT EXISTS bookings (id VARCHAR(100) PRIMARY KEY, lead_id VARCHAR(100), lead_name VARCHAR(500), customer_name VARCHAR(500), mobile VARCHAR(100), customer_mobile VARCHAR(100), customer_email VARCHAR(500), project_name VARCHAR(500), unit_id VARCHAR(100), unit_number VARCHAR(500), unit_name VARCHAR(500), flat_type VARCHAR(500), floor INT, booking_amount DECIMAL(18,2), total_price DECIMAL(18,2), booking_date VARCHAR(100), status VARCHAR(500), created_at VARCHAR(64), updated_at VARCHAR(64));
CREATE TABLE IF NOT EXISTS payments (id VARCHAR(100) PRIMARY KEY, booking_id VARCHAR(100), lead_id VARCHAR(100), lead_name VARCHAR(500), customer_name VARCHAR(500), mobile VARCHAR(100), customer_mobile VARCHAR(100), customer_email VARCHAR(500), project_name VARCHAR(500), unit_number VARCHAR(500), unit_name VARCHAR(500), installment_type VARCHAR(500), total_cost DECIMAL(18,2), amount DECIMAL(18,2), pending_amount DECIMAL(18,2), due_date VARCHAR(100), payment_date VARCHAR(100), mode VARCHAR(500), reference VARCHAR(500), remarks TEXT, created_at VARCHAR(64), updated_at VARCHAR(64));
CREATE TABLE IF NOT EXISTS documents (id VARCHAR(100) PRIMARY KEY, customer_id VARCHAR(100), customer_name VARCHAR(500), pan VARCHAR(500), aadhaar VARCHAR(500), passport_photo VARCHAR(500), address_proof VARCHAR(500), income_proof VARCHAR(500), bank_statement VARCHAR(500), pan_path VARCHAR(1000), pan_filename VARCHAR(500), pan_content_type VARCHAR(200), pan_size BIGINT, aadhaar_path VARCHAR(1000), aadhaar_filename VARCHAR(500), aadhaar_content_type VARCHAR(200), aadhaar_size BIGINT, passport_photo_path VARCHAR(1000), passport_photo_filename VARCHAR(500), passport_photo_content_type VARCHAR(200), passport_photo_size BIGINT, address_proof_path VARCHAR(1000), address_proof_filename VARCHAR(500), address_proof_content_type VARCHAR(200), address_proof_size BIGINT, income_proof_path VARCHAR(1000), income_proof_filename VARCHAR(500), income_proof_content_type VARCHAR(200), income_proof_size BIGINT, bank_statement_path VARCHAR(1000), bank_statement_filename VARCHAR(500), bank_statement_content_type VARCHAR(200), bank_statement_size BIGINT, remarks TEXT, created_at VARCHAR(64), updated_at VARCHAR(64));
CREATE TABLE IF NOT EXISTS loans (id VARCHAR(100) PRIMARY KEY, customer_id VARCHAR(100), customer_name VARCHAR(500), bank_name VARCHAR(500), loan_amount DECIMAL(18,2), emi DECIMAL(18,2), sanction_date VARCHAR(100), status VARCHAR(500), remarks TEXT, created_at VARCHAR(64), updated_at VARCHAR(64));
CREATE TABLE IF NOT EXISTS agreements (id VARCHAR(100) PRIMARY KEY, booking_id VARCHAR(100), lead_id VARCHAR(100), lead_name VARCHAR(500), customer_name VARCHAR(500), mobile VARCHAR(100), customer_mobile VARCHAR(100), customer_email VARCHAR(500), project_name VARCHAR(500), unit_number VARCHAR(500), unit_name VARCHAR(500), agreement_number VARCHAR(500), agreement_date VARCHAR(100), stamp_duty DECIMAL(18,2), registration_date VARCHAR(100), registration_number VARCHAR(500), agreement_value DECIMAL(18,2), status VARCHAR(500), remarks TEXT, created_at VARCHAR(64), updated_at VARCHAR(64));
CREATE TABLE IF NOT EXISTS possessions (id VARCHAR(100) PRIMARY KEY, booking_id VARCHAR(100), customer_name VARCHAR(500), unit_number VARCHAR(500), final_inspection BOOLEAN, utility_connection BOOLEAN, key_handover BOOLEAN, possession_letter BOOLEAN, status VARCHAR(500), handover_date VARCHAR(100), created_at VARCHAR(64), updated_at VARCHAR(64));
CREATE TABLE IF NOT EXISTS support_tickets (id VARCHAR(100) PRIMARY KEY, customer_name VARCHAR(500), mobile VARCHAR(100), email VARCHAR(500), unit_number VARCHAR(500), type VARCHAR(500), subject VARCHAR(500), description TEXT, status VARCHAR(500), assigned_to VARCHAR(500), resolution TEXT, created_at VARCHAR(64), updated_at VARCHAR(64));
CREATE TABLE IF NOT EXISTS employees (id VARCHAR(100) PRIMARY KEY, employee_code VARCHAR(500), name VARCHAR(500), department VARCHAR(500), designation VARCHAR(500), mobile VARCHAR(100), email VARCHAR(500), doj VARCHAR(100), basic_salary DECIMAL(18,2), hra DECIMAL(18,2), allowances DECIMAL(18,2), bank_account VARCHAR(500), ifsc VARCHAR(500), pan VARCHAR(500), aadhaar VARCHAR(500), pf_number VARCHAR(500), esic_number VARCHAR(500), created_at VARCHAR(64), updated_at VARCHAR(64));
CREATE TABLE IF NOT EXISTS attendance (id VARCHAR(100) PRIMARY KEY, employee_id VARCHAR(100), employee_name VARCHAR(500), date VARCHAR(100), status VARCHAR(500), check_in VARCHAR(100), check_out VARCHAR(100), leave_type VARCHAR(500), overtime_hours DECIMAL(18,2), remarks TEXT, created_at VARCHAR(64), updated_at VARCHAR(64));
CREATE TABLE IF NOT EXISTS salary_runs (id VARCHAR(100) PRIMARY KEY, employee_id VARCHAR(100), employee_name VARCHAR(500), month VARCHAR(100), basic DECIMAL(18,2), hra DECIMAL(18,2), incentives DECIMAL(18,2), commission DECIMAL(18,2), bonus DECIMAL(18,2), gross DECIMAL(18,2), deductions DECIMAL(18,2), pf DECIMAL(18,2), esic DECIMAL(18,2), professional_tax DECIMAL(18,2), advance_recovery DECIMAL(18,2), net DECIMAL(18,2), status VARCHAR(500), paid_date VARCHAR(100), payment_mode VARCHAR(500), created_at VARCHAR(64), updated_at VARCHAR(64));
CREATE TABLE IF NOT EXISTS vendors (id VARCHAR(100) PRIMARY KEY, name VARCHAR(500), company VARCHAR(500), category VARCHAR(500), gst VARCHAR(500), pan VARCHAR(500), contact_person VARCHAR(500), mobile VARCHAR(100), email VARCHAR(500), bank_account VARCHAR(500), ifsc VARCHAR(500), address TEXT, created_at VARCHAR(64), updated_at VARCHAR(64));
CREATE TABLE IF NOT EXISTS purchase_orders (id VARCHAR(100) PRIMARY KEY, vendor_id VARCHAR(100), vendor_name VARCHAR(500), po_number VARCHAR(500), po_date VARCHAR(100), amount DECIMAL(18,2), status VARCHAR(500), description TEXT, remarks TEXT, created_at VARCHAR(64), updated_at VARCHAR(64));
CREATE TABLE IF NOT EXISTS vendor_bills (id VARCHAR(100) PRIMARY KEY, vendor_id VARCHAR(100), vendor_name VARCHAR(500), bill_number VARCHAR(500), invoice_number VARCHAR(500), bill_date VARCHAR(100), invoice_date VARCHAR(100), bill_amount DECIMAL(18,2), gst DECIMAL(18,2), paid_amount DECIMAL(18,2), balance DECIMAL(18,2), status VARCHAR(500), due_date VARCHAR(100), remarks TEXT, created_at VARCHAR(64), updated_at VARCHAR(64));
CREATE TABLE IF NOT EXISTS vendor_payments (id VARCHAR(100) PRIMARY KEY, bill_id VARCHAR(100), bill_number VARCHAR(500), vendor_id VARCHAR(100), vendor_name VARCHAR(500), vendor_mobile VARCHAR(100), payment_date VARCHAR(100), mode VARCHAR(500), paid_amount DECIMAL(18,2), balance_amount DECIMAL(18,2), payment_status VARCHAR(500), utr VARCHAR(500), bank VARCHAR(500), remarks TEXT, created_at VARCHAR(64), updated_at VARCHAR(64));
CREATE TABLE IF NOT EXISTS petty_cash_entries (id VARCHAR(100) PRIMARY KEY, date VARCHAR(100), voucher_number VARCHAR(500), category VARCHAR(500), amount DECIMAL(18,2), payment_mode VARCHAR(500), employee_name VARCHAR(500), requested_by VARCHAR(500), approved_by VARCHAR(500), description TEXT, remarks TEXT, created_at VARCHAR(64), updated_at VARCHAR(64));
CREATE TABLE IF NOT EXISTS unit_photos (id VARCHAR(100) PRIMARY KEY, unit_id VARCHAR(100), unit_number VARCHAR(500), caption VARCHAR(500), taken_at VARCHAR(100), data_base64 TEXT, size DECIMAL(18,2), created_at VARCHAR(64), updated_at VARCHAR(64));
